require("user.options")
require("user.lazy")
require("user.keymaps")
require("user.telescope")
require("user.treesitter")
require("user.cmp")
require("user.ufo_folding")
-- require("user.harpoon")
require("user.lsp")
require("user.todo")
require("user.oil")
-- require("user.lazygit")
