# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
eval "$(oh-my-posh init bash --config ~/.themes/gruvbox.omp.json)"

# aliases
alias lla='ls -a'
alias denv='docker attach d.env'
alias mongo-start='$MONGODIR/bin/mongod.exe --storageEngine wiredTiger --dbpath $MONGODIR/database/WiredTiger'
alias geo_vis='node ~/repos/toolkit/node/app/app.js'
alias charm='~/appdata/local/jetbrains/pycharm\ 2023.2/bin/pycharm64.exe'